# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    admin.continent:
        class: App\Admin\ContinentAdmin
        arguments: [~, App\Entity\Place, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: places, label: Continent }
        public: true

    admin.country:
        class: App\Admin\CountryAdmin
        arguments: [~, App\Entity\Place, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: places, label: Country }
        public: true

    admin.region:
        class: App\Admin\RegionAdmin
        arguments: [~, App\Entity\Place, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: places, label: Region }
        public: true

    admin.city:
        class: App\Admin\CityAdmin
        arguments: [~, App\Entity\Place, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: places, label: City }
        public: true

    admin.exchange:
        class: App\Admin\ExchangeAdmin
        arguments: [~, App\Entity\Exchange, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: places, label: Exchange }
        public: true

    admin.order_type:
        class: App\Admin\OrderTypeAdmin
        arguments: [~, App\Entity\OrderType, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: exchange, label: OrderType }
        public: true

#    admin.city:
#        class: App\Admin\CityAdmin
#        arguments: [~, App\Entity\Place, App\Controller\CityAdminController]
#        tags:
#            - { name: sonata.admin, manager_type: orm, group: admin, label: Place }
#        public: true

    admin.currency:
        class: App\Admin\CurrencyAdmin
        arguments: [~, App\Entity\Currency, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Currency }
        public: true

    admin.rate:
        class: App\Admin\RateAdmin
        arguments: [~, App\Entity\Rate, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Rate }
        public: true
